Add lab#1
MaximShuvalov/mmd-pib-17i1-shuvalov pull request #1
Opened 2020-09-01 05:32 UTC by MaximShuvalov

2020-09-15 03:24 UTC, ydvorzhetskiy requested changes

2020-09-15 03:24 UTC, ydvorzhetskiy commented on lab#1/Calc.java
> +public class Calc {
Не могу написать к предыдущему файлу - оставлю здесь.
В репохиторий не нужно выкладывать бинарные файлы, нужно добавить все в .gitignore

2020-09-15 03:24 UTC, ydvorzhetskiy commented on lab#1/Calc.java
> +        System.out.println("Ответ = " + Calculate(args[0], args[1], args[2]));
А если аргументов будет два?

2020-09-15 03:24 UTC, ydvorzhetskiy commented on lab#1/Calc.java
> +            case "+": {
Сравнение строчек работает медленно. Рекоменду использовать char - это, кстати, требуется и в условии.

2020-09-15 03:24 UTC, ydvorzhetskiy commented on lab#1/Calc.java
> +                    throw new IllegalArgumentException("Делить на 0 нельзя!!");
0. Круто! Хоть по условию NaN, но эксепшен - это есчо круче.
1. Зачем-то Вы сравниваете оба аргумента)
2. Да, и double так просто не сравнить с 0.0 - используйте, какую-нибудь погрешность - типа 1e-12

2020-09-15 04:43 UTC, MaximShuvalov commented on lab#1/Calc.java
> -                if (cD > - eps && cd < eps )
При сравнении по модулю никогда не зайдет в ветку условия, т.е. исключение не сработает.

2020-09-17 09:47 UTC, ydvorzhetskiy approved these changes

2020-09-17 09:47 UTC, ydvorzhetskiy commented on lab#1/Calc.java
> +                if (cD < eps)
Не запушили изменения, где (cD > -eps) && (cD < eps)

2020-09-29 03:00 UTC, merged